# Generated by Django 5.2.4 on 2025-08-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_created_alter_order_checkout_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
