# Generated by Django 5.2.4 on 2025-08-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_checkout_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_link_url',
            field=models.URLField(blank=True, help_text='Square-hosted checkout page URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='checkout_id',
            field=models.CharField(blank=True, help_text='Square checkout link ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
